export const data = {
  personal: {
    name: "Dr. A Gyan Sirohi",
    firstName: "A Gyan",
    lastName: "Sirohi",
    title: "Dr.",
    designation: "Assistant Professor – Entomology",
    department: "Department of Agriculture / Entomology",
    institution: "Geeta University, Panipat, Haryana",
    email: "gyansirohi@gmail.com",
    phone: "+91-8630585854",
    alternatePhone: "+91-9639503048",
    dob: "20 March 1997",
    gender: "Male",
    nationality: "Indian",
    hometown: "Village & Post Shyampur Jatt, District Hapur – 245205, Uttar Pradesh, India",
    currentLocation: "Panipat, Haryana, India",
    languages: ["English", "Hindi", "Punjabi"],
    specializations: [
      "Ph.D. in Entomology",
      "Crop Protection",
      "Integrated Pest Management (IPM)",
      "Agri-AI & Drone Tech",
      "Basmati Rice Pest Complex",
      "Biopesticides & Botanicals",
    ],
    areasOfInterest: [
      "Agricultural Entomology",
      "Plant Protection Techniques",
      "Organic & Sustainable Farming",
      "Indoor & Vertical Farming",
      "Contract Farming",
      "Extension Services & Rural Outreach",
      "Sports & Student Wellness",
    ],
  },

  stats: [
    { number: "14", suffix: "+", label: "Students Mentored", icon: "👨‍🎓" },
    { number: "8", suffix: "", label: "Institutional Roles", icon: "🏛️" },
    { number: "3", suffix: "", label: "Research Papers", icon: "📄" },
    { number: "5", suffix: "", label: "Book Chapters", icon: "📚" },
    { number: "1", suffix: "", label: "Patent Filed", icon: "💡" },
    { number: "6", prefix: "₹", suffix: " Cr", label: "DBT-BIRAC PI Proposal", icon: "🌾" },
  ],

  profile: `Ph.D. in Entomology and Assistant Professor at Geeta University, Panipat, with hands-on experience in teaching undergraduate agriculture, curriculum development, student mentoring, and academia–industry liaison.

Research strengths center in integrated pest management (IPM), biopesticides, and the insect-pest complex of basmati rice, supported by 3 peer-reviewed research papers, 5 academic book chapters, a breakthrough patent for an automated Brown Plant Hopper monitoring device, and a ₹6 crore DBT–BIRAC Bio-AI Moolankur Hub proposal as Principal Investigator.

Passionate about bridging field entomology with cutting-edge artificial intelligence, spectral diagnostics, and drone-based precision delivery to transform modern crop protection and sustainable agriculture.`,

  education: [
    {
      period: "2022 – 2026",
      degree: "Ph.D. in Entomology",
      institution: "Sardar Vallabhbhai Patel University of Agriculture and Technology (SVPUAT)",
      location: "Meerut, Uttar Pradesh, India",
      grade: "CGPA 7.34",
      highlight: "Doctoral Research on Basmati Rice Insect-Pest Complex & Biopesticides",
      status: "Completed / Submitted",
    },
    {
      period: "2020 – 2022",
      degree: "M.Sc. in Entomology",
      institution: "Chaudhary Charan Singh University (CCSU)",
      location: "Meerut, Uttar Pradesh, India",
      grade: "CGPA 8.72",
      highlight: "First Class with Distinction | Advanced Insect Physiology & Biological Control",
      status: "First Division",
    },
    {
      period: "2013 – 2017",
      degree: "B.Sc. (Hons.) Agriculture",
      institution: "Sardar Vallabhbhai Patel University of Agriculture and Technology (SVPUAT)",
      location: "Meerut, Uttar Pradesh, India",
      grade: "CGPA 6.59",
      highlight: "Comprehensive agronomy, soil science, plant protection, and farm management",
      status: "First Division",
    },
    {
      period: "2012 – 2013",
      degree: "Intermediate (12th)",
      institution: "IIMT Academy",
      location: "Meerut, Uttar Pradesh, India",
      grade: "64.00%",
      highlight: "Science & Biology Stream",
      status: "First Division",
    },
    {
      period: "2010 – 2011",
      degree: "High School (10th)",
      institution: "K.V. Public School",
      location: "Meerut, Uttar Pradesh, India",
      grade: "CGPA 7.50",
      highlight: "Science & Mathematics Foundation",
      status: "First Division",
    },
  ],

  experience: [
    {
      period: "January 2026 – Present",
      title: "Assistant Professor – Entomology",
      org: "School of Agriculture, Geeta University",
      location: "Panipat, Haryana",
      current: true,
      desc: "Leading undergraduate teaching and research in Entomology, Plant Pathology, Food Science, and Agronomy with emphasis on experiential hands-on field learning.",
      responsibilities: [
        "Teaching undergraduate agriculture courses with modern pedagogies, experiential demonstrations, and laboratory modules.",
        "Guiding laboratory sessions, field visits, rural internships, student projects, and actively mentoring 14 B.Sc. (Hons.) Agriculture students.",
        "Spearheading academic planning, course delivery, and development/revision of Ph.D. curricula in Plant Pathology & Entomology.",
        "Fostering academia–industry linkages with top agro-chemical firms and government research centers for MoUs, internships, and placements.",
        "Serving on multiple university statutory committees, IQAC quality mandates, student welfare, and international conferences.",
      ],
    },
    {
      period: "Jan – Jun 2017 (6 Months)",
      title: "Experiential Learning in Mushroom Cultivation Technology",
      org: "Sardar Vallabhbhai Patel University of Agriculture and Technology",
      location: "Meerut, Uttar Pradesh",
      current: false,
      desc: "Intensive 6-month hands-on project encompassing planning, spawn production, substrate preparation, harvest, post-harvest packaging, marketing, and commercial farm economics.",
      responsibilities: [
        "Compost preparation, pasteurization, spawning, and climatic regulation for high-yield oyster and button mushrooms.",
        "Disease and pest management in commercial mushroom grow rooms without harmful chemical residue.",
        "Supply chain, packaging, direct market sales, and collaborative team-based agribusiness management.",
      ],
    },
    {
      period: "Jul – Dec 2016 (6 Months)",
      title: "Rural Agricultural Work Experience (RAWE)",
      org: "Krishi Vigyan Kendra (KVK)",
      location: "Saharanpur, Uttar Pradesh",
      current: false,
      desc: "Extensive rural field immersion program working alongside farmers, extension specialists, and agricultural officers.",
      responsibilities: [
        "Village attachments, farmer surveys, pest incidence diagnostic camps, and socio-economic farm appraisals.",
        "Demonstrated Integrated Pest Management (IPM) practices and biopesticide preparation to marginal farmers.",
        "Conducted farmer-scientist interactions, soil testing campaigns, and harvest advisory sessions.",
      ],
    },
  ],

  institutionalRoles: [
    {
      title: "Placement Coordinator",
      dept: "Corporate Relations & Training",
      icon: "💼",
      badge: "Industry Liaison",
      desc: "Active liaison with leading agro-industries, bio-fertilizer enterprises, and national agricultural institutions for corporate MoUs, summer internships, industrial exposure visits, and on-campus recruitment.",
    },
    {
      title: "DSW Coordinator",
      dept: "Dean of Student Welfare",
      icon: "🤝",
      badge: "Student Affairs",
      desc: "Spearheading student welfare programs, student grievances, club activities, leadership development, cultural fests, and multi-faceted youth engagement initiatives.",
    },
    {
      title: "Event Coordinator",
      dept: "University Events & Co-Curriculars",
      icon: "🎪",
      badge: "Organization",
      desc: "Conceptualizing, planning, and executing national seminars, technical workshops, distinguished guest lectures, farmer awareness days, and mega university co-curricular conclaves.",
    },
    {
      title: "Admission Coordinator",
      dept: "Academic Outreach",
      icon: "🎯",
      badge: "Outreach & Growth",
      desc: "Driving regional admissions campaigns, student counseling, career guidance sessions with prospective candidates and parents, and university promotional drives.",
    },
    {
      title: "IQAC Coordinator",
      dept: "Internal Quality Assurance Cell",
      icon: "📋",
      badge: "Accreditation & Curriculum",
      desc: "Managing quality assurance frameworks, course outcomes, accreditation documentation, and the foundational revision/formulation of Ph.D. curricula in Plant Pathology & Entomology.",
    },
    {
      title: "In-Charge, Wet Laboratory",
      dept: "School of Agriculture Facilities",
      icon: "🧪",
      badge: "Lab Administration",
      desc: "Overseeing day-to-day operations, state-of-the-art diagnostic instruments, chemical inventories, safety protocols, and student practical demonstrations in the central wet laboratory.",
    },
    {
      title: "Co-In-Charge, Mushroom Lab",
      dept: "Hands-on Agribusiness Unit",
      icon: "🍄",
      badge: "Production & Training",
      desc: "Managing experimental mushroom production setups, substrate sterilization, spawn maintenance, and conducting specialized hands-on cultivation training for students and local growers.",
    },
    {
      title: "Mentor, B.Sc. (Hons.) Agriculture",
      dept: "Student Mentorship Program",
      icon: "🌱",
      badge: "Mentorship",
      desc: "Direct mentor and academic counselor to 14 undergraduate agriculture students, tracking academic progress, research aptitude, career goals, and personal development.",
    },
  ],

  projects: [
    {
      id: "agrosense-ai",
      title: "AgroSense-AI",
      subtitle: "Autonomous Drone-Mounted Platform for Early Pest Detection & Precision Delivery",
      fundingBody: "DBT–BIRAC Bio-AI Moolankur Hub",
      role: "Principal Investigator (PI)",
      budget: "₹6 Crore (₹60,000,000)",
      duration: "30 Months",
      leadInstitution: "Geeta University, Panipat",
      badge: "Mega Flagship R&D",
      status: "Proposal Submitted / Under Review",
      technologies: [
        "Artificial Intelligence / Deep Learning",
        "Hyperspectral Imaging",
        "NIR / MIR Spectroscopy",
        "Thermal Infrared",
        "Autonomous UAVs (Drones)",
        "GPS / RTK Precision Navigation",
        "LiDAR 3D Canopy Profiling",
        "Targeted Micro-Spraying of Microbial Bio-pesticides",
      ],
      description:
        "A revolutionary high-tech precision agriculture initiative engineered to detect agricultural pests and fungal/bacterial diseases at pre-symptomatic physiological stages. By coupling multi-modal aerial sensors (hyperspectral, thermal, LiDAR) with lightweight edge AI models on autonomous drones, the system pinpoints micro-infestations across vast basmati rice and cash crop fields, triggering targeted, micro-dosed delivery of biological and botanical inputs without chemical drift.",
      impact: [
        "Pre-symptomatic detection of lethal insect pests like Brown Plant Hopper (BPH) and stem borers.",
        "Up to 80% reduction in chemical insecticide application via micro-targeted precision bio-formulations.",
        "Zero environmental residue, safeguarding groundwater and beneficial entomofauna (honeybees, predators).",
        "Real-time farmer mobile dashboard with GIS pest heatmaps and actionable spray prescription.",
      ],
    },
    {
      id: "ai-crop-protection",
      title: "AI-Based Crop Pest & Disease Detection Platform",
      subtitle: "Cloud & Edge Intelligent Computer Vision for Field-Level Diagnosis",
      fundingBody: "Geeta University / Ag-Tech Research Lab",
      role: "Developer / Academic Lead",
      budget: "Institutional AgTech Grant",
      duration: "Ongoing Initiative",
      leadInstitution: "Geeta University",
      badge: "Web Platform & AI App",
      status: "Active Deployment",
      technologies: [
        "Deep Convolutional Neural Networks (CNNs)",
        "Mobile-First Web App (PWA)",
        "Economic Threshold Level (ETL) Engine",
        "Multi-lingual Diagnostic Output",
        "Integrated Pest Management (IPM) Advisory",
        "Cloud Image Storage & Analytics",
      ],
      description:
        "A farmer-centric digital crop-protection ecosystem designed to deliver instantaneous, laboratory-grade pest and symptom identification from simple smartphone photographs. The engine cross-references pest severity against validated Economic Threshold Levels (ETL) and auto-generates balanced IPM recommendations encompassing cultural, biological, botanical, and emergency chemical remedies.",
      impact: [
        "Instantaneous field diagnostics eliminating multi-day lab testing delays.",
        "Empowers marginal farmers with scientifically verified IPM schedules tailored to their crop stage.",
        "Democratizes access to PhD-level entomological expertise in local languages.",
      ],
    },
  ],

  publications: [
    {
      id: "R1",
      code: "R1",
      type: "paper",
      category: "Research Paper",
      title:
        "Study of the insect-pest complex associated with basmati rice (Oryza sativa L.) in the basmati-growing belt of western Uttar Pradesh, India.",
      authors: "Dr. A Gyan Sirohi et al.",
      journal: "Leading Agricultural & Entomological Research Journal",
      year: "2024 – 2025",
      tags: ["Basmati Rice", "Insect-Pest Complex", "Western UP", "Population Dynamics", "Field Survey"],
      highlight: "Comprehensive ecological census across major basmati clusters of Western UP",
      desc: "Detailed multi-season investigation characterizing incidence, seasonality, and damage thresholds of primary and secondary insect pests attacking aromatic basmati rice varieties under irrigated ecosystems.",
    },
    {
      id: "R2",
      code: "R2",
      type: "paper",
      category: "Research Paper",
      title:
        "Efficacy of biopesticides and botanical insecticides against major insect-pests of basmati rice (Oryza sativa L.).",
      authors: "Dr. A Gyan Sirohi et al.",
      journal: "Crop Protection & Sustainable Pest Management Journal",
      year: "2024 – 2025",
      tags: ["Biopesticides", "Botanical Insecticides", "Neem Extracts", "Microbial Control", "IPM"],
      highlight: "High efficacy biological alternatives to hazardous synthetic pyrethroids",
      desc: "Evaluated bio-efficacy of entomopathogenic fungi (Beauveria bassiana, Metarhizium anisopliae) alongside neem-based azadirachtin formulations, showing exceptional control of foliage feeders with zero ecological harm.",
    },
    {
      id: "R3",
      code: "R3",
      type: "paper",
      category: "Research Paper",
      title:
        "Seasonal population dynamics of yellow stem borer and rice leaf folder in relation to weather parameters in basmati rice.",
      authors: "Dr. A Gyan Sirohi et al.",
      journal: "Agrometeorology & Entomology Journal",
      year: "2024 – 2025",
      tags: ["Yellow Stem Borer", "Rice Leaf Folder", "Weather Correlation", "Peak Abundance", "Forecasting"],
      highlight: "Correlated temperature, humidity, and rainfall patterns with pest population spikes",
      desc: "Statistical modeling correlating weekly meteorological indices with yellow stem borer (Scirpophaga incertulas) and leaf folder (Cnaphalocrocis medinalis) catches, yielding reliable predictive early-warning pest alerts.",
    },
    {
      id: "B1",
      code: "B1",
      type: "book",
      category: "Book Chapter",
      title: "Bio-inputs and bio-formulations: today and future perspectives.",
      authors: "Dr. A Gyan Sirohi et al.",
      publisher: "Academic & Scientific Book Publications",
      year: "2025",
      tags: ["Bio-inputs", "Bio-formulations", "Nanobio-pesticides", "Microbial Strains"],
      desc: "Comprehensive review detailing novel carrier materials, shelf-life stabilization technologies, nano-encapsulation methods, and future regulatory pathways for microbial bio-inputs in sustainable farming.",
    },
    {
      id: "B2",
      code: "B2",
      type: "book",
      category: "Book Chapter",
      title: "Bio-based solutions for climate change mitigation in agriculture.",
      authors: "Dr. A Gyan Sirohi et al.",
      publisher: "Sustainable Agricultural Science Editions",
      year: "2025",
      tags: ["Climate Change", "Carbon Sequestration", "Bio-solutions", "Resilient Ag"],
      desc: "Explores the dual role of biological pest protection and soil microbiome augmentation in lowering agricultural carbon emissions and conferring climate resilience against extreme weather stresses.",
    },
    {
      id: "B3",
      code: "B3",
      type: "book",
      category: "Book Chapter",
      title: "AI tools in agriculture.",
      authors: "Dr. A Gyan Sirohi et al.",
      publisher: "Smart Agriculture & Tech Series",
      year: "2024",
      tags: ["Artificial Intelligence", "Computer Vision", "Smart Farming", "Sensor Networks"],
      desc: "Synthesizes modern AI frameworks, edge algorithms, and drone-based multispectral sensor workflows for automated pest recognition, weed mapping, and precision resource allocation in field crops.",
    },
    {
      id: "B4",
      code: "B4",
      type: "book",
      category: "Book Chapter",
      title: "Major insect pests of field, vegetable, and fruit crops.",
      authors: "Dr. A Gyan Sirohi et al.",
      publisher: "Comprehensive Agricultural Entomology Handbooks",
      year: "2024",
      tags: ["Field Crops", "Vegetable Pests", "Fruit Borers", "Diagnostic Keys"],
      desc: "An authoritative visual diagnostic and management manual detailing life cycles, symptoms of damage, economic thresholds, and holistic IPM matrices for 60+ economically significant pest species.",
    },
    {
      id: "B5",
      code: "B5",
      type: "book",
      category: "Book Chapter",
      title: "Integrated pest management in cropping systems.",
      authors: "Dr. A Gyan Sirohi et al.",
      publisher: "Global Agro-Ecology Series",
      year: "2023",
      tags: ["IPM Systems", "Cultural Controls", "Parasitoids", "Ecosystem Balance"],
      desc: "Details multi-tiered IPM deployment strategies integrating crop rotation, trap crops, pheromone traps, conservation biocontrol, and targeted biorationals across diverse agro-climatic zones.",
    },
    {
      id: "P1",
      code: "P1",
      type: "patent",
      category: "Patent",
      title: "Automated Monitoring Device for Early Detection of Brown Plant Hopper (BPH) in Basmati Rice Crops.",
      authors: "Dr. A Gyan Sirohi et al.",
      org: "Indian Patent Office / Govt. of India",
      year: "2025 – 2026",
      tags: ["Patent", "BPH Detection", "Optical Traps", "Automated Sensor", "Basmati Rice"],
      highlight: "Breakthrough patented smart hardware combining optical attractants with micro-sensors",
      desc: "A solar-assisted field-installable automated sensory device configured with specific wavelength light emission, automated digital counting sensors, and telemetry alerts for early detection of Brown Plant Hopper (Nilaparvata lugens) before severe hopper burn occurs.",
    },
  ],

  patentData: {
    title: "Automated Monitoring Device for Early Detection of Brown Plant Hopper (BPH) in Basmati Rice Crops",
    code: "Patent ID: P1",
    status: "Published / Filed — Patent Office, Government of India",
    leadInventor: "Dr. A Gyan Sirohi",
    domain: "Smart Agro-Electronics & Entomological Surveillance",
    summary:
      "A novel, low-power autonomous field device engineered with optical wavelength attractants, digital infrared barrier sensors, and IoT wireless telemetry to detect and record nymphal and adult BPH densities in real-time. Automatically notifies agronomists and farmers when pest numbers surpass Economic Threshold Levels (ETL).",
    features: [
      "Targeted multi-spectral LED attractant tuned to Nilaparvata lugens phototactic receptors",
      "Solar-powered battery array for uninterrupted round-the-clock remote field operations",
      "Automated optical counting chamber immune to dust, rain, and humidity disturbances",
      "Cellular / LoRaWAN telemetry transmitting immediate SMS and smartphone alerts to farmers",
      "Prevents extensive hopper-burn crop losses in premium basmati growing tracts",
    ],
  },

  skills: {
    coreCompetencies: [
      { name: "Insect-Pest Identification & Taxonomy", level: 96, category: "entomology" },
      { name: "Integrated Pest Management (IPM)", level: 95, category: "entomology" },
      { name: "Biopesticides & Botanical Insecticides", level: 92, category: "entomology" },
      { name: "Field Population Dynamics & ETL Analysis", level: 90, category: "research" },
      { name: "Mushroom Production & Spawn Technology", level: 90, category: "production" },
      { name: "AI Tools & Computer Vision in Crop Protection", level: 88, category: "tech" },
      { name: "Curriculum Development & IQAC Documentation", level: 92, category: "academic" },
      { name: "Research Proposal Writing (DBT/BIRAC/ICAR)", level: 94, category: "research" },
      { name: "MS Office, Scientific Graphics & Data Analysis", level: 90, category: "tech" },
    ],
    technicalDomains: [
      {
        title: "Entomological Research",
        icon: "🔬",
        skills: [
          "Insect rearing & bioassay protocols",
          "Taxonomic dissection & identification",
          "Brown Plant Hopper (BPH) monitoring",
          "Stem borer & leaf folder dynamics",
          "Entomopathogenic fungi cultivation",
        ],
      },
      {
        title: "Agri-AI & Smart Technology",
        icon: "🤖",
        skills: [
          "AI/CNN image-based disease models",
          "Drone multi-sensor crop monitoring",
          "Hyperspectral & Thermal data interpretation",
          "Digital trap telemetry & ETL trigger engines",
          "Smart farm data workflows",
        ],
      },
      {
        title: "Mushroom & Farm Science",
        icon: "🍄",
        skills: [
          "Substrate formulation & pasteurization",
          "Oyster & button mushroom cultivation",
          "Spawn preparation & contamination control",
          "Post-harvest processing & marketing",
          "Wet laboratory instrument maintenance",
        ],
      },
      {
        title: "Academic & Institutional",
        icon: "🎓",
        skills: [
          "NEP-2020 curriculum alignment",
          "Undergraduate pedagogy & mentorship",
          "Ph.D. syllabus revision & course files",
          "Corporate MoU & placement coordination",
          "National conference & seminar organization",
        ],
      },
    ],
    laboratoryEquipment: [
      "Stereo Zoom Research Microscopes",
      "Insect Breeding & Rearing Cages",
      "Autoclaves & Laminar Air Flow Chambers",
      "Digital Spectrophotometers",
      "Automated Light & Pheromone Traps",
      "Mushroom Substrate Pasteurization Units",
      "Thermal & NIR Sensor Probes",
      "Micro-Applicators & Rotary Spray Towers",
      "Centrifuges & Precision Digital Balances",
    ],
  },

  fdp: {
    title: "UGC-FDP on NEP-2020: Orientation & Sensitization",
    grade: "GRADE A+",
    organizer:
      "UGC–Malaviya Mission Teacher Training Programme (UGC-MMTTP), Jai Narain Vyas University, Jodhpur, Rajasthan",
    dates: "30 January – 07 February 2026",
    status: "Successfully Completed with Distinction",
    description:
      "Intensive faculty training program focusing on outcome-based education, multidisciplinary curricula design under NEP-2020, pedagogical innovations, modern evaluation frameworks, and high-impact research ethics.",
  },

  computerCourse: {
    title: "Course on Computer Concepts (CCC)",
    authority: "National Institute of Electronics & Information Technology (NIELIT)",
    completionDate: "September 2018",
    status: "Completed & Certified",
    skillsCovered: "Operating Systems, Word Processing, Spreadsheets, Databases, Networking, and Digital Financial Services",
  },

  awards: [
    {
      type: "academic",
      badge: "1st Prize",
      title: "1st Prize — Oral Presentation",
      event:
        "International Conference SEABTMG-2025 (Sustainable Environments for Agriculture, Bio-diversity, Technology and Market for Next Generation)",
      venue: "Himachal Pradesh University, Shimla",
      dates: "13–14 September 2025",
      icon: "🏆",
      desc: "Conferred 1st Prize for research presentation demonstrating breakthrough sustainable pest management and bio-formulations in basmati agro-ecosystems.",
    },
    {
      type: "academic",
      badge: "2nd Prize",
      title: "2nd Prize — Poster Presentation",
      event:
        "ICAR-sponsored National Symposium on Sustainable Agriculture Practices for Food Security and Environmental Conservation",
      venue: "College of Agriculture, SVPUAT, Meerut",
      dates: "15–16 March 2024",
      icon: "🥈",
      desc: "Awarded 2nd Prize for scientific poster showcasing population fluctuations of key lepidopteran borers and biopesticidal suppression methods.",
    },
    {
      type: "sports",
      badge: "1st Place",
      title: "1st Place — Kabaddi",
      event: "Annual Games and Sports Meet 2023–24",
      venue: "Sardar Vallabhbhai Patel University of Agriculture and Technology, Meerut",
      dates: "27–29 December 2023",
      icon: "🥇",
      desc: "Champions in university-wide competitive inter-college Kabaddi tournament displaying outstanding team strategy and athleticism.",
    },
    {
      type: "sports",
      badge: "Winner",
      title: "Winner — Cricket Championship",
      event: "Inter-Hostel Cricket Tournament Final",
      venue: "SVPUAT, Meerut",
      dates: "14 June 2014",
      icon: "🏏",
      desc: "Led the hostel squad to victory in the university tournament championship final match.",
    },
    {
      type: "sports",
      badge: "1st Place",
      title: "1st Place — Junior Boys (55 kg Category)",
      event: "National Karate-Do Championship",
      venue: "Amritsar, Punjab",
      dates: "3–4 December 2011",
      icon: "🥋",
      desc: "National Gold Medalist in competitive Karate-Do martial arts championship.",
    },
  ],

  workshops: [
    {
      date: "21–22 Apr 2026",
      type: "Certificate",
      title: "Workshop on Food Processing and Product Development",
      organizer: "School of Agriculture, Geeta University, Panipat",
      badge: "Food Science",
    },
    {
      date: "16–17 Apr 2025",
      type: "Certificate",
      title:
        "ICAR-sponsored National Symposium: Next Generation Horticulture and Livestock Farming (NGA-2025)",
      organizer: "Jointly organised by SVPUA&T, Meerut and SIDAVES, Jammu",
      badge: "ICAR Symposium",
    },
    {
      date: "21 Feb 2025",
      type: "Participated",
      title: "Workshop on Financial Awareness and Banking Products",
      organizer: "College of Agriculture, SVPUAT, Meerut",
      badge: "Financial Literacy",
    },
    {
      date: "21 Dec 2024",
      type: "Certificate",
      title: "SAMAGAM-2024: First Alumni Meet",
      organizer: "SVPUAT, Meerut",
      badge: "Alumni Relations",
    },
    {
      date: "9–11 Dec 2024",
      type: "Participated",
      title: "Workshop on AI & Machine Learning for Agricultural Sciences (AIML4Agris)",
      organizer: "College of Technology, SVPUAT, Meerut",
      badge: "AI & ML in Agriculture",
    },
    {
      date: "15–16 Mar 2024",
      type: "Certificate",
      title:
        "ICAR-sponsored National Symposium on Sustainable Agriculture Practices for Food Security & Environment Conservation",
      organizer: "COA-SVPUAT, Meerut",
      badge: "Certificate of Appreciation",
    },
    {
      date: "2024",
      type: "Participated",
      title: "Workshop on Intellectual Property Rights (IPR) in Agricultural Research",
      organizer:
        "Council of Science and Technology, U.P. & Dept. of Genetics & Plant Breeding, SVPUAT, Meerut",
      badge: "Patents & IPR",
    },
    {
      date: "9 Jan 2024",
      type: "Participated",
      title: "Conclave on Sustainability, Productivity and Green Growth",
      organizer: "SVPUAT, Meerut in collaboration with IPL Centre for Rural Outreach",
      badge: "Green Growth",
    },
    {
      date: "27–28 May 2023",
      type: "Participated",
      title: "Workshop on Climate Resilient and Smart Agriculture",
      organizer: "College of Agriculture, SVPUAT, Meerut",
      badge: "Climate Smart Ag",
    },
  ],

  sportsParticipation: [
    {
      date: "20–24 Feb 2023",
      title: "21st All India Agricultural Universities Sports and Games Meet 2022-23",
      venue: "CCS Haryana Agricultural University, Hisar",
      scope: "National Level Inter-University Representation",
      icon: "🏃‍♂️",
    },
    {
      date: "7–10 Nov 2012",
      title: "Inter-School Sports and Games Competition 2012-13",
      venue: "Shanti Niketan Vidyapeeth, Meerut",
      scope: "Recognised by Ministry of Youth Affairs and Sports, Govt. of India",
      icon: "🎯",
    },
    {
      date: "17–19 Oct 2012",
      title: "Under-19 Inter-School Sports and Games Competition 2012-13",
      venue: "IIMT Academy, Meerut",
      scope: "Recognised by Ministry of Youth Affairs and Sports, Govt. of India",
      icon: "🏅",
    },
  ],

  declaration: {
    statement:
      "I hereby declare that the information provided above is true and correct to the best of my knowledge and belief.",
    place: "Panipat, Haryana",
    date: "21 September 2026",
    signatory: "Dr. A Gyan Sirohi",
    designation: "Assistant Professor – Entomology",
  },
};
